<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Spm;
use App\Models\Sp2d;
use Carbon\Carbon;

class DummyReportSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tahun = 2026;
        $satkerIds = [1, 2, 3, 4, 5];
        $userId = 1;
        $ppkId = 1;

        for ($bulan = 1; $bulan <= 12; $bulan++) {
            $jumlahTransaksi = rand(3, 8);
            
            for ($i = 0; $i < $jumlahTransaksi; $i++) {
                $tanggalAcak = rand(1, 25);
                $spmDate = Carbon::create($tahun, $bulan, $tanggalAcak);
                
                $slaDays = rand(1, 6);
                $sp2dDate = (clone $spmDate)->addDays($slaDays);
                
                if ($sp2dDate->year > $tahun) {
                    $sp2dDate = Carbon::create($tahun, 12, 31);
                }

                $satkerId = $satkerIds[array_rand($satkerIds)];
                $nilai = rand(15, 250) * 1000000;
                
                $spm = Spm::create([
                    'nomor_spm' => 'SPM/DUMMY/' . $tahun . '/' . str_pad($bulan, 2, '0', STR_PAD_LEFT) . '/' . rand(1000, 9999),
                    'tahun_anggaran' => (string) $tahun,
                    'jenis_spm' => 'LS',
                    'tanggal_spm' => $spmDate->toDateString(),
                    'nilai_spm' => $nilai,
                    'jenis_tagihan' => 'Tagihan Dummy untuk Skripsi',
                    'keterangan' => 'Generated by Seeder',
                    'status' => 'Terverifikasi',
                    'uploaded_by' => $userId,
                    'satker_id' => $satkerId,
                    'ppk_id' => $ppkId
                ]);
                
                Sp2d::create([
                    'nomor_sp2d' => 'SP2D/DUMMY/' . $tahun . '/' . str_pad($bulan, 2, '0', STR_PAD_LEFT) . '/' . rand(1000, 9999),
                    'tanggal_sp2d' => $sp2dDate->toDateString(),
                    'nilai_sp2d' => $nilai,
                    'spm_id' => $spm->id,
                    'keterangan' => 'Generated by Seeder',
                    'file_pdf' => 'sp2d/dummy.pdf',
                    'status' => 'Terverifikasi',
                    'uploaded_by' => $userId,
                ]);
            }
        }
    }
}
